### ISSUE TITLE
Space as OR splitter

### ISSUE THREAD

**Issue by andydavidson-turbulenz** [IPWright83/VSFileNav#11]
It would be useful to have the space character default to splitting the search into multiple terms, any of which can be present in the searched file name:
e.g: Searching for "complex name" would find "mycomplexname.cpp", "mysimplename.cpp", "mycomplexandlongname.cpp", "anamethatiscomplexandlong.cpp" and "my complex name.cpp"

This effectively extends the "Space as a wildcard" issue by not enforcing ordering in the searched strings.

**Comment by IPWright83** [comment]
Could you explain the use case a bit more? Are you trying to find multiple files? Or just a single file but you're unsure on the name?

**Comment by andydavidson-turbulenz** [comment]
It should find multiple files, although I'm probably only looking for one in most cases. I've used this feature (in Visual Assist's file finder) to effectively search by a number of keywords. So I might type "pudding manager system" to try and locate a pudding related system I'm pretty sure exists, but I don't know the name of. This might then show:
puddingmanagement,cpp (note: management/manager didn't match here, but pudding did)
breakfastmanger.cpp
puddingconsumption.cpp
ultraviolencesystem.cpp

So from that I probably want to start looking through puddingmanagement.cpp.

In essence "show me anything that might be related to any of my search criteria".

**Comment by IPWright83** [comment]
@andydavidson-turbulenz I decided this seemed a good idea so I've implemented it. I've just got a little work to do on creating an updated installer.

**Comment by IPWright83** [comment]
@andydavidson-turbulenz the visual studio gallery is encountering errors right now. But if you want the latest copy you can grab it from https://dl.dropboxusercontent.com/u/41796243/VSNav-Latest.vsix

**Comment by andydavidson-turbulenz** [comment]
Awesome! Thanks very much! :)
