### ISSUE TITLE
Compatibility with VS 2015

### ISSUE THREAD

**Issue by dvdnhm** [IPWright83/VSFileNav#14]
Hello,

Could you make it compatible with VS 2015 please?

Thanks

**Comment by IPWright83** [comment]
@dvdnhm if you use the following link it should take you to a version which installs with VS2015. If this doesn't work then re-open and we can try to work out why.

https://visualstudiogallery.msdn.microsoft.com/57278574-d596-4f3c-8d1a-fc5e571c9a31

**Comment by dvdnhm** [comment]
I found the extention on visual studio gallery, and this is the file I downloaded:
https://visualstudiogallery.msdn.microsoft.com/cfdf85c2-aaa4-4bdd-b8ea-e22bcc9860af
https://visualstudiogallery.msdn.microsoft.com/cfdf85c2-aaa4-4bdd-b8ea-e22bcc9860af/file/46028/5/VSNav.vsix

in case you need to update the file on that platform..

thanks

**Comment by IPWright83** [comment]
@dvdnhm thanks, I'll take a look. I'm in talks with the Visual Studio guys because it won't let me update that project (keeps encountering an error).

**Comment by IPWright83** [comment]
@dvdnhm in the mean time try using this link https://github.com/IPWright83/VSFileNav/blob/master/VSNav.vsix

**Comment by dvdnhm** [comment]
it works thanks
